"""Create sport table

Revision ID: 58e7b5a8a1ce
Revises: be12f68d5aa4
Create Date: 2024-08-14 04:00:42.696101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e7b5a8a1ce'
down_revision = 'be12f68d5aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('distant', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=2500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport')
    # ### end Alembic commands ###
