"""empty message

Revision ID: 64aa650390f6
Revises: eb9e0968417d
Create Date: 2024-11-30 12:27:29.940517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64aa650390f6'
down_revision = 'eb9e0968417d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_model', schema=None) as batch_op:
        batch_op.drop_column('users')

    # ### end Alembic commands ###
