"""empty message

Revision ID: 684d21592078
Revises: 8cefa197c9ef
Create Date: 2024-06-20 17:53:47.612363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684d21592078'
down_revision = '8cefa197c9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('name2', sa.String(length=250), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('creator', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscribed', sa.Boolean(), nullable=True))
        batch_op.drop_column('sex')
        batch_op.drop_column('name2')
        batch_op.drop_column('name')
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name2', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sex', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('subscribed')
        batch_op.drop_column('creator')
        batch_op.drop_column('admin')
        batch_op.drop_column('info')

    op.drop_table('info')
    # ### end Alembic commands ###
