"""Add note

Revision ID: 8a8abe568f6b
Revises: 66bfe0b80feb
Create Date: 2025-03-11 08:57:36.829227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8abe568f6b'
down_revision = '66bfe0b80feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('userId', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
