"""empty message

Revision ID: a23581e3e342
Revises: 76d502993c82
Create Date: 2024-06-20 17:10:27.626651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23581e3e342'
down_revision = '76d502993c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
