"""empty message

Revision ID: bc2bbb728a0a
Revises: 
Create Date: 2024-08-03 01:58:18.933912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2bbb728a0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('users')
    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=1000),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='uni_users_email')
    )
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=10000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='news_pkey')
    )
    # ### end Alembic commands ###
