"""empty message

Revision ID: bd7e5f9c2eb1
Revises: 684d21592078
Create Date: 2024-06-20 21:27:35.379698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7e5f9c2eb1'
down_revision = '684d21592078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.String(length=250), nullable=True),
    sa.Column('countDone', sa.Integer(), nullable=True),
    sa.Column('countUnDone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.String(length=250), nullable=True))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.String(length=250), nullable=True))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.String(length=250), nullable=True))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('userId')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('userId',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('userId')

    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('userId')

    op.drop_table('task_stat')
    # ### end Alembic commands ###
