"""empty message

Revision ID: be12f68d5aa4
Revises: bc2bbb728a0a
Create Date: 2024-08-14 03:48:25.749014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be12f68d5aa4'
down_revision = 'bc2bbb728a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('sport')

    # ### end Alembic commands ###
