"""empty message

Revision ID: dcee387b6945
Revises: 9a60aa8bee6a
Create Date: 2024-08-02 22:37:43.538576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcee387b6945'
down_revision = '9a60aa8bee6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.Boolean(), nullable=True))
        batch_op.drop_column('tasks')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasks', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('task')

    with op.batch_alter_table('economy', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=1000),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
