"""empty message

Revision ID: e066e90eb900
Revises: 18c49ed6c2ca
Create Date: 2024-06-20 15:43:39.411898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e066e90eb900'
down_revision = '18c49ed6c2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('timer', sa.Boolean(), nullable=True),
    sa.Column('tasks', sa.Boolean(), nullable=True),
    sa.Column('economy', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('packages')

    op.drop_table('packages')
    # ### end Alembic commands ###
