"""empty message

Revision ID: eb9e0968417d
Revises: 58e7b5a8a1ce
Create Date: 2024-11-30 11:53:32.822865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9e0968417d'
down_revision = '58e7b5a8a1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userOwnerId', sa.String(length=250), nullable=True),
    sa.Column('inviteKey', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('columns', sa.String(length=250), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('team')

    op.drop_table('team_model')
    # ### end Alembic commands ###
